# Generated by Django 3.2 on 2021-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantityLeft', models.PositiveIntegerField()),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
