# Generated by Django 3.2 on 2021-04-23 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='mainImage',
        ),
        migrations.RemoveField(
            model_name='store',
            name='quantityLeft',
        ),
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('quantityLeft', models.PositiveIntegerField()),
                ('dateIntroduced', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
