# Generated by Django 3.2 on 2021-04-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210423_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='quantityLeft',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='store',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='store',
            field=models.ManyToManyField(null=True, to='store.Store'),
        ),
    ]
