# Generated by Django 3.2 on 2021-04-23 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_storeitem_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='store',
            field=models.ManyToManyField(blank=True, related_name='items', to='store.Store'),
        ),
    ]
