# Generated by Django 3.2 on 2021-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210423_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
