# Generated by Django 3.2 on 2021-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210512_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='longditude',
            field=models.CharField(default='', max_length=50),
        ),
    ]
