# Generated by Django 3.2 on 2021-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_store_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='visible',
        ),
        migrations.AddField(
            model_name='store',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
