# Generated by Django 3.2 on 2021-06-03 02:20

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210526_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='mainImage',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
