# Generated by Django 3.2 on 2021-06-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_storeitem_mainimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.CharField(default='', max_length=50)),
                ('longditude', models.CharField(default='', max_length=50)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
