# Generated by Django 3.2 on 2021-06-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_news_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='store',
            name='hidden',
        ),
        migrations.AddField(
            model_name='pub',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
