# Generated by Django 3.2 on 2021-06-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210610_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylocation',
            name='latitude',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mylocation',
            name='longditude',
            field=models.CharField(default='', max_length=50),
        ),
    ]
